name: Wheels
on: push

jobs:

  build-wheels:
    name: Build wheels for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]

    env:
      CIBW_SKIP: "cp312-* pp* *-manylinux_i686 *-musllinux_i686 *-win32"
      CIBW_ARCHS_MACOS: x86_64

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Install premake5
        uses: abel0b/setup-premake@v2.3
        with:
          version: "5.0.0-beta2"

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2

      - name: Upload wheel artifacts
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: ./wheelhouse/*.whl


  build-sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install premake5
        uses: abel0b/setup-premake@v2.3
        with:
          version: "5.0.0-beta2"

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: dist/*.tar.gz
